-- FOOD_INFO : 음식 정보 테이블 ❌ => 음식 즐겨찾기
-- ㄴ 아무 데이터가 안들어가는 테이블이라서 식단관리 즐겨찾기 음식 테이블로 바꿨습니다. 

-- 1. 기존 테이블 완전 삭제
DROP TABLE food_info CASCADE CONSTRAINTS;

-- 2. 새로운 테이블 생성 (즐겨찾기 기능 포함)
CREATE TABLE favorite_food_info (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name VARCHAR2(100) NOT NULL,
    calories NUMBER(5) NOT NULL,
    count NUMBER(5) DEFAULT 0,
    customer_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);

-- 3. 인덱스 추가 (성능 향상)
CREATE INDEX idx_favorite_food_info_customer ON favorite_food_info(customer_id);
CREATE INDEX idx_favorite_food_info_food_name ON favorite_food_info(food_name);
CREATE INDEX idx_favorite_food_info_created_at ON favorite_food_info(created_at);

-- 4. 확인
SELECT * FROM favorite_food_info;